table DataQualityIssues
	lineageTag: fc6fdf21-cf7e-4455-a158-4fe416730352

	measure 'Total DQ Issues' =
			
			COALESCE(
			    COUNTROWS(DataQualityIssues),
			    0
			)
		formatString: 0
		lineageTag: 82ddb086-f78f-4cc3-83f8-a53e82706b0d

	measure 'Submissions with DQ Issues' =
			
			DISTINCTCOUNT(DataQualityIssues[source_row_number])
		formatString: 0
		lineageTag: 369f6eb1-74ef-400f-b01b-aaa92c612791

	measure 'DQ Issue Rate' =
			
			DIVIDE(
			    [Submissions with DQ Issues],
			    [Expected Submissions]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: c81d8ab8-c996-4aee-af75-d1c4b3d56ce9

	measure 'High-Severity DQ Issues' =
			
			CALCULATE(
			    [Total DQ Issues],
			    DataQualityIssues[severity] = "High"
			)
		formatString: 0
		lineageTag: fa39af9e-4b18-4987-b1b0-a9386abd5032

	measure 'Missing Evidence Issues' =
			
			CALCULATE(
			    [Total DQ Issues],
			    DataQualityIssues[rule] = "DQ-004 Missing Evidence"
			)
		formatString: 0
		lineageTag: dc68d1e4-7416-4f4c-b863-4d4321cac471

	column issue_id
		dataType: string
		lineageTag: 44fa79d1-2a92-436a-8832-4e94f91a7cd8
		summarizeBy: none
		sourceColumn: issue_id

		annotation SummarizationSetBy = Automatic

	column submission_id
		dataType: string
		lineageTag: 950d6cbc-9163-444a-9832-521da505e954
		summarizeBy: none
		sourceColumn: submission_id

		annotation SummarizationSetBy = Automatic

	column control_id
		dataType: string
		lineageTag: 2bb1fb29-d38f-4178-9353-cac61a795191
		summarizeBy: none
		sourceColumn: control_id

		annotation SummarizationSetBy = Automatic

	column source_row_number
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ed8c74b8-538e-4670-b11c-3a9e9c49a58c
		summarizeBy: none
		sourceColumn: source_row_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column rule
		dataType: string
		lineageTag: d247a4ed-2262-4090-afdc-6cc4c8b98815
		summarizeBy: none
		sourceColumn: rule

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		lineageTag: 9f2c4164-c07e-40ea-92f9-c76ce27e037d
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = Automatic

	column field
		dataType: string
		lineageTag: 803f2e5e-6b35-43d1-9f2b-6df901bb2bcc
		summarizeBy: none
		sourceColumn: field

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: b6fc70d6-7e3a-4583-9e1d-7281c5652964
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	partition DataQualityIssues = m
		mode: import
		source =
				let
				    Source =
				        Csv.Document(
				            File.Contents(DataRoot & "\data_quality_issues.csv"),
				            [
				                Delimiter = ",",
				                Encoding = 65001,
				                QuoteStyle = QuoteStyle.Csv
				            ]
				        ),
				
				    PromotedHeaders =
				        Table.PromoteHeaders(
				            Source,
				            [PromoteAllScalars = true]
				        ),
				
				    BlankToNull =
				        Table.ReplaceValue(
				            PromotedHeaders,
				            "",
				            null,
				            Replacer.ReplaceValue,
				            Table.ColumnNames(PromotedHeaders)
				        ),
				
				    Typed =
				        Table.TransformColumnTypes(
				            BlankToNull,
				            {
				                {"issue_id", type text},
				                {"submission_id", type text},
				                {"control_id", type text},
				                {"source_row_number", Int64.Type},
				                {"rule", type text},
				                {"severity", type text},
				                {"field", type text},
				                {"message", type text}
				            },
				            "en-US"
				        )
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

